### ISSUE TITLE
Config Parser for ipWhiteList sourceRange fails for YAML list

### ISSUE THREAD

**Issue by lyrixderaven** [alexandreh2ag/traefik-ipfilter-basicauth#3]
The config parser `NewChecker` in https://github.com/alexandreh2ag/traefik-ipfilter-basicauth/blob/1b724039b0579023b66b684b3be963a75faee808/checker.go#L17 fails for the list format YAML syntax of the sourceRange key. 

For this example middleware configuration:

```
http:
  middlewares:
    my_whitelist_basicauth:
      plugin:
        traefik-ipfilter-basicauth:
          basicAuth:
            realm: MyRealm
            usersFile: "/etc/traefik/.htpasswd"
          ipWhiteList:
            sourceRange:
              - 127.0.0.1
              - 192.168.1.1/24
```

the parser produces this debug output:

```
traefik_node_1-traefik-proxy-node-1-1  | time="2023-01-03T10:31:34Z" level=error msg="cannot parse CIDR whitelist [║24║127.0.0.1/32║192.168.1.1/24]: parsing CIDR trusted IPs <nil>: invalid CIDR address: ║24║127.0.0.1/32║192.168.1.1/24" routerName=my_router_net@file entryPointName=websecure
```

I'm not a go developer, so I'm struggling to debug this and suggest a fix, but it does appear to me that somehow, the parser yields a `||` separated list starting with an empty IP and the `24` CIDR postfix, which then fails the validation. Neither a list solely consisting of IP addresses (without the CIDR postfixes) nor a list with only fully qualified CIDR ranges changes this behavior; there always remains an empty `║24║` entry at the beginning of the CIDR whitelist.

Since the set of whitelisted IPs can become quite large, stuffing it all into a single line (e.g., `sourceRange: "127.0.0.1/32,192.168.1.1/24"`) won't be very practical, and multi-line YAML lists would improve readability.

**Comment by alexandreh2ag** [comment]
Hello @lyrixderaven,

Thank you to your feed back.

I just test the example you provide but it seems to work for me.
Cloud you give me more detail like : 
- traefik version
- OS
- How traefik is run (docker / binnary / etc)

I have not try this plugin on newest version of traefik, maybe something change.

**Comment by alexandreh2ag** [comment]
I did some test and i found that plugin is not working with traefik versions 2.6.2 and <2.8.2.

**Comment by lyrixderaven** [comment]
I'm running this in traefik:v2.9, within a docker container on a current Ubuntu Jammy host; the config file for the middleware (incl. the plugin) is mounted as a directory bind mount into the container.  A minimal example would be this `docker-compose.yml`:

```
version: '3'

services:
  traefik-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    ports:
    #   # The HTTP port
      - "80:80"
    # The HTTPS port
      - "443:443"
    # The Web UI
      - "8080:8080"
    volumes:
      # Main configuration file - static configuration
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      # .htaccess configuration: Default: user 'wienfluss' -> PW 'Streak.Monopoly.Caress3'
      - ./config/htpasswd/.htpasswd:/etc/traefik/.htpasswd:ro
      # Middleware Configuration Files
      - ./config/middlewares:/etc/traefik/middlewares
```
and this traefik.yml file 

```
providers:
  file:
    watch: true
    directory: "/etc/traefik/config"

api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

  traefik:
    address: ":8080"

log:
  level: DEBUG

experimental:
  plugins:
    traefik-ipfilter-basicauth:
      moduleName: "github.com/alexandreh2ag/traefik-ipfilter-basicauth"
      version: "v1.0.3"
```
as well as the `middleware.yml` I provided above. Hope that helps?
